# Generated by Django 3.1.7 on 2021-02-28 15:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, verbose_name='Event Name')),
                ('data', models.TextField(verbose_name='About')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=150)),
                ('image', models.FileField(upload_to='event/%Y/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=[], message='Select valid Image.')])),
            ],
        ),
        migrations.CreateModel(
            name='UserLikeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
    ]
